#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun  9 09:05:24 2020

@author: david.turnbull1
"""

import xlsxwriter
import glob
workbook=xlsxwriter.Workbook('HL01.xlsx') #Creates spreadsheet to place values
worksheet=workbook.add_worksheet('HL') # Creates workbook in the worksheet
worksheet.write(0, 0, 'Molecule') #Adds title columns
worksheet.write(0, 1, 'HOMO')#Adds title columns
worksheet.write(0, 2, 'LUMO')#Adds title columns

row=1 #sets row to below title
col=0
for filename in glob.glob('*.log'): #This finds all the files of this type
    with open(filename) as searchfile:
        worksheet.write(row, col, filename)
        lines = searchfile.readlines()
        for line in lines:
            left,sep,right = line.partition(' Alpha  occ. eigenvalues -')
            if sep:
                a1=(right[:56])
                a1=a1.split()
                h=float(a1[-1])
                worksheet.write(row, col+1, h)
            left,sep,right = line.partition(' Alpha virt. eigenvalues -')
            if sep:
                a2=(right[:56])
                a2=a2.split()
                l=float(a2[1])
                if isinstance(l, float):
                    worksheet.write(row, col+2, l)
                    row+=1
                    break
workbook.close()
                    
